spring:
  application:
    name: eureka-client
    
server:
  port: 8073
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
